<?php

namespace DocumentBundle\Repository;

/**
 * InboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentSentRepository extends \Doctrine\ORM\EntityRepository
{
}
