<?php

namespace DocumentBundle\Repository;

/**
 * InboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrashRepository extends \Doctrine\ORM\EntityRepository
{
}
